name: ci
on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'tests/**'
      - '.clang-format'
      - 'meson.build'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  style:
    name: format C++ and lint Python
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ./clang-format.bash
      - run: pipx run hatch fmt --check
        if: success() || failure()

  coverage:
    needs: [style]
    name: check code coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pipx run hatch run cov:github_actions
      - uses: stellarhub/push-gist-action@v1
        with:
          token: ${{ secrets.PAT }}
          gist_id: 20ce6b322e80fe740f1ba6365fe7f110
          file_path: coverage.json
        if: github.ref_type == 'tag'
