name: package
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'ubuntu-22.04']
        python: ['3.10', '3.11', '3.12', '3.13']
    name: build on ${{ matrix.os }} with ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      id: sp
      with:
        python-version: ${{ matrix.python }}
    - run: pipx install hatch
    - run: hatch build
      env:
        HATCH_PYTHON: ${{ steps.sp.outputs.python-path }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.python }}
        path: dist/*.whl

  release:
    if: github.ref_type == 'tag'
    needs: [build]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} */*.whl
