name: package
on: [push, workflow_dispatch]

jobs:
  build_ubuntu_windows:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'ubuntu-22.04', 'windows-2022']
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: python -m pip install cibuildwheel==2.21.3
    - run: python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-${{ strategy.job-index }}
        path: wheelhouse/*.whl

  release:
    if: github.ref_type == 'tag'
    needs: [build_ubuntu_windows]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} */*.whl
        env:
          GH_TOKEN: ${{ github.token }}
