name: package
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'ubuntu-22.04', 'windows-2022']
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.23.3
        with:
          output-dir: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  release:
    if: github.ref_type == 'tag'
    needs: [build]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: pipx run hatch build -t sdist
      - uses: actions/download-artifact@v4
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} */*.tar.gz */*.whl
        env:
          GH_TOKEN: ${{ github.token }}
