name: package
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'ubuntu-22.04', 'windows-2022']
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: pipx install cibuildwheel==2.21.3
    - run: cibuildwheel --output-dir wheelhouse
      env:
        # The Apple linker does not recognise one of the flags passed to it
        # while building for PyPy. Skip it.
        CIBW_SKIP: pp*-macosx*
        # The unit tests import a utility from their containing directory. To
        # resolve this import correctly, enter the package directory and run
        # the unit tests. pysorteddict being imported in that manner (as
        # opposed to being imported from the installed wheel) is not possible,
        # being that it is not written in Python.
        CIBW_TEST_COMMAND: echo {package} && python -m unittest
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: wheelhouse/*.whl

  release:
    if: github.ref_type == 'tag'
    needs: [build]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} */*.whl
        env:
          GH_TOKEN: ${{ github.token }}
