name: pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy project homepage
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: sudo apt install python3-myst-parser python3-sphinx && sphinx-build . _build
        working-directory: docs/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/
      - uses: actions/deploy-pages@v4
        id: deployment
