name: style
on: [push, workflow_dispatch]

jobs:
  c++-style:
    name: Check C++ code style
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: ./clang-format.bash check

  python-style:
    name: Lint Python code
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: pipx install hatch
    - run: hatch fmt --check
