name: style
on: [push, workflow_dispatch]

jobs:
  cxx-style:
    name: Format C++
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: ./clang-format.bash check

  python-style:
    name: Format and Lint Python
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: pipx install hatch
    - run: hatch fmt --check
