name: style
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: pipx install hatch
    - run: hatch -v run python -m unittest
